// apps/solid/src/adapters/solid/CanvasAppProvider.tsx
import {
  type CanvasApp,
  canvasSliceKeys,
  createCanvasSliceSubscriptionManager,
} from '@infinite-canvas-x/canvas-app'
import { createEffect, createMemo, createSignal, type JSX, onCleanup } from 'solid-js'

import { CanvasAppContext } from './CanvasAppContext'
import { CanvasSliceManagerContext } from './CanvasSliceManagerContext'
import { CanvasSlicesContext, createCanvasSliceAccessors } from './CanvasSlicesContext'

type Props = {
  app: CanvasApp | null
  children: JSX.Element
}

export function CanvasAppProvider(props: Props) {
  const sliceManager = createCanvasSliceSubscriptionManager()
  const { accessors: sliceAccessors, setSlice } = createCanvasSliceAccessors()
  const [app, setApp] = createSignal<CanvasApp | null>(props.app)

  const sliceUnsubscribes: Array<() => void> = []

  function clearSliceSubscriptions() {
    while (sliceUnsubscribes.length > 0) {
      sliceUnsubscribes.pop()?.()
    }
  }

  function bindSliceRefs() {
    clearSliceSubscriptions()

    for (const key of canvasSliceKeys) {
      setSlice(key, sliceManager.get(key))
      sliceUnsubscribes.push(
        sliceManager.subscribe(key, () => {
          setSlice(key, sliceManager.get(key))
        }),
      )
    }
  }

  function teardownSliceSubscriptions() {
    clearSliceSubscriptions()
    sliceManager.detach()
  }

  createEffect(() => {
    const nextApp = props.app
    setApp(nextApp)
    teardownSliceSubscriptions()

    if (!nextApp) {
      return
    }

    nextApp.attachKeyboardListeners()
    sliceManager.attach(nextApp.state)
    bindSliceRefs()

    onCleanup(() => {
      teardownSliceSubscriptions()
      nextApp.destroy()
    })
  })

  const appAccessor = createMemo(() => app())

  return (
    <CanvasAppContext.Provider value={appAccessor}>
      <CanvasSliceManagerContext.Provider value={sliceManager}>
        <CanvasSlicesContext.Provider value={sliceAccessors}>
          {props.children}
        </CanvasSlicesContext.Provider>
      </CanvasSliceManagerContext.Provider>
    </CanvasAppContext.Provider>
  )
}

// apps/svelte/src/adapters/svelte/CanvasAppProvider.svelte
<script lang="ts">
import {
  type CanvasApp,
  canvasSliceKeys,
  createCanvasSliceSubscriptionManager,
} from '@infinite-canvas-x/canvas-app'
import type { Snippet } from 'svelte'
import { onDestroy } from 'svelte'

import { setCanvasAppContext } from './context'
import type { CanvasSliceKey, CanvasSliceRefMap } from './keys'
import { createDefaultSliceRefs } from './sliceRefs'

type Props = {
  app?: CanvasApp | null
  children?: Snippet
}

let { app = null, children }: Props = $props()

let appRef = $state<CanvasApp | null>(null)
let slices = $state(createDefaultSliceRefs())
const sliceManager = createCanvasSliceSubscriptionManager()
const sliceUnsubscribes: Array<() => void> = []

function setSliceValue<K extends CanvasSliceKey>(key: K, value: CanvasSliceRefMap[K]) {
  slices[key] = value
}

function clearSliceSubscriptions() {
  while (sliceUnsubscribes.length > 0) {
    sliceUnsubscribes.pop()?.()
  }
}

function bindSliceRefs() {
  clearSliceSubscriptions()

  for (const key of canvasSliceKeys) {
    setSliceValue(key, sliceManager.get(key) as CanvasSliceRefMap[typeof key])
    sliceUnsubscribes.push(
      sliceManager.subscribe(key, () => {
        setSliceValue(key, sliceManager.get(key) as CanvasSliceRefMap[typeof key])
      }),
    )
  }
}

function teardownSliceSubscriptions() {
  clearSliceSubscriptions()
  sliceManager.detach()
  slices = createDefaultSliceRefs()
}

setCanvasAppContext({
  getApp: () => appRef,
  getSlices: () => slices,
  sliceManager,
})

let previousApp: CanvasApp | null = null

$effect(() => {
  const next = app
  if (previousApp === next) {
    return
  }

  previousApp?.destroy()
  teardownSliceSubscriptions()
  appRef = next

  if (next) {
    next.attachKeyboardListeners()
    sliceManager.attach(next.state)
    bindSliceRefs()
  }

  previousApp = next
})

onDestroy(() => {
  teardownSliceSubscriptions()
  app?.destroy()
})
</script>

{@render children?.()}
