// apps/vue/src/adapters/vue/CanvasAppProvider.vue
<script setup lang="ts">
import {
  type CanvasApp,
  canvasSliceDefinitions,
  canvasSliceKeys,
  createCanvasSliceSubscriptionManager,
} from '@infinite-canvas-x/canvas-app'
import { onUnmounted, provide, shallowRef, watch } from 'vue'

import {
  CanvasAppKey,
  CanvasSliceManagerKey,
  type CanvasSliceRefMap,
  CanvasSliceRefsKey,
} from './keys'

const props = defineProps<{
  app: CanvasApp | null
}>()

const appRef = shallowRef<CanvasApp | null>(props.app)
const sliceManager = createCanvasSliceSubscriptionManager()

const sliceRefs = Object.fromEntries(
  canvasSliceKeys.map((key) => [key, shallowRef(canvasSliceDefinitions[key].defaults)]),
) as CanvasSliceRefMap

const sliceUnsubscribes: Array<() => void> = []

function clearSliceSubscriptions() {
  while (sliceUnsubscribes.length > 0) {
    sliceUnsubscribes.pop()?.()
  }
}

function bindSliceRefs() {
  clearSliceSubscriptions()

  for (const key of canvasSliceKeys) {
    sliceRefs[key].value = sliceManager.get(key)
    sliceUnsubscribes.push(
      sliceManager.subscribe(key, () => {
        sliceRefs[key].value = sliceManager.get(key)
      }),
    )
  }
}

function teardownSliceSubscriptions() {
  clearSliceSubscriptions()
  sliceManager.detach()
  for (const key of canvasSliceKeys) {
    sliceRefs[key].value = canvasSliceDefinitions[key].defaults
  }
}

watch(
  () => props.app,
  (next, prev) => {
    prev?.destroy()
    appRef.value = next
    teardownSliceSubscriptions()

    if (next) {
      next.attachKeyboardListeners()
      sliceManager.attach(next.state)
      bindSliceRefs()
    }
  },
  { immediate: true },
)

provide(CanvasAppKey, appRef)
provide(CanvasSliceManagerKey, sliceManager)
provide(CanvasSliceRefsKey, sliceRefs)

onUnmounted(() => {
  teardownSliceSubscriptions()
  props.app?.destroy()
})
</script>

<template>
  <slot />
</template>

// apps/svelte/src/adapters/svelte/CanvasAppProvider.svelte
<script lang="ts">
import {
  type CanvasApp,
  canvasSliceKeys,
  createCanvasSliceSubscriptionManager,
} from '@infinite-canvas-x/canvas-app'
import type { Snippet } from 'svelte'
import { onDestroy } from 'svelte'

import { setCanvasAppContext } from './context'
import type { CanvasSliceKey, CanvasSliceRefMap } from './keys'
import { createDefaultSliceRefs } from './sliceRefs'

type Props = {
  app?: CanvasApp | null
  children?: Snippet
}

let { app = null, children }: Props = $props()

let appRef = $state<CanvasApp | null>(null)
let slices = $state(createDefaultSliceRefs())
const sliceManager = createCanvasSliceSubscriptionManager()
const sliceUnsubscribes: Array<() => void> = []

function setSliceValue<K extends CanvasSliceKey>(key: K, value: CanvasSliceRefMap[K]) {
  slices[key] = value
}

function clearSliceSubscriptions() {
  while (sliceUnsubscribes.length > 0) {
    sliceUnsubscribes.pop()?.()
  }
}

function bindSliceRefs() {
  clearSliceSubscriptions()

  for (const key of canvasSliceKeys) {
    setSliceValue(key, sliceManager.get(key) as CanvasSliceRefMap[typeof key])
    sliceUnsubscribes.push(
      sliceManager.subscribe(key, () => {
        setSliceValue(key, sliceManager.get(key) as CanvasSliceRefMap[typeof key])
      }),
    )
  }
}

function teardownSliceSubscriptions() {
  clearSliceSubscriptions()
  sliceManager.detach()
  slices = createDefaultSliceRefs()
}

setCanvasAppContext({
  getApp: () => appRef,
  getSlices: () => slices,
  sliceManager,
})

let previousApp: CanvasApp | null = null

$effect(() => {
  const next = app
  if (previousApp === next) {
    return
  }

  previousApp?.destroy()
  teardownSliceSubscriptions()
  appRef = next

  if (next) {
    next.attachKeyboardListeners()
    sliceManager.attach(next.state)
    bindSliceRefs()
  }

  previousApp = next
})

onDestroy(() => {
  teardownSliceSubscriptions()
  app?.destroy()
})
</script>

{@render children?.()}
