// apps/svelte/src/ui/primitives/toggle-group/ToggleGroup.svelte
<script lang="ts">
import { ToggleGroup } from 'bits-ui'
import type { Snippet } from 'svelte'

import { cn } from '@/shared/lib/utils'

import { setToggleGroupContext } from './toggleGroupContext'
import type { ToggleVariants } from './toggleVariants'

type Props = {
  type?: 'single' | 'multiple'
  value?: string | string[]
  variant?: ToggleVariants['variant']
  size?: ToggleVariants['size']
  class?: string
  children?: Snippet
}

let {
  type = 'single',
  value = $bindable<string | string[]>(type === 'multiple' ? [] : ''),
  variant = 'default',
  size = 'default',
  class: className,
  children,
}: Props = $props()

$effect(() => {
  setToggleGroupContext({ variant, size })
})
</script>

{#if type === 'multiple'}
  <ToggleGroup.Root
    data-slot="toggle-group"
    type="multiple"
    bind:value={value as string[]}
    data-variant={variant}
    data-size={size}
    class={cn(
      'group/toggle-group flex w-fit items-center rounded-md data-[variant=outline]:shadow-xs',
      className,
    )}
  >
    {@render children?.()}
  </ToggleGroup.Root>
{:else}
  <ToggleGroup.Root
    data-slot="toggle-group"
    type="single"
    bind:value={value as string}
    data-variant={variant}
    data-size={size}
    class={cn(
      'group/toggle-group flex w-fit items-center rounded-md data-[variant=outline]:shadow-xs',
      className,
    )}
  >
    {@render children?.()}
  </ToggleGroup.Root>
{/if}

// apps/vue/src/ui/primitives/toggle-group/ToggleGroup.vue
<script setup lang="ts">
import { ToggleGroupRoot } from 'reka-ui'
import { computed, provide } from 'vue'

import { cn } from '@/shared/lib/utils'

import type { ToggleVariants } from './toggleVariants'

const props = withDefaults(
  defineProps<{
    type?: 'single' | 'multiple'
    modelValue?: string | string[]
    variant?: ToggleVariants['variant']
    size?: ToggleVariants['size']
    class?: string
  }>(),
  {
    type: 'single',
    variant: 'default',
    size: 'default',
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string | string[]]
}>()

provide('toggleGroupContext', { variant: props.variant, size: props.size })

const rootClasses = computed(() =>
  cn(
    'group/toggle-group flex w-fit items-center rounded-md data-[variant=outline]:shadow-xs',
    props.class,
  ),
)
</script>

<template>
  <ToggleGroupRoot
    data-slot="toggle-group"
    :type="type"
    :model-value="modelValue"
    :data-variant="variant"
    :data-size="size"
    :class="rootClasses"
    @update:model-value="emit('update:modelValue', $event as string & string[])"
  >
    <slot />
  </ToggleGroupRoot>
</template>
