// apps/svelte/src/ui/primitives/toggle-group/ToggleGroupItem.svelte
<script lang="ts">
import { ToggleGroup } from 'bits-ui'
import type { Snippet } from 'svelte'

import { cn } from '@/shared/lib/utils'

import { getToggleGroupContext } from './toggleGroupContext'
import { toggleItemClasses } from './toggleVariants'

let {
  value,
  class: className,
  children,
  onclick,
  ...restProps
}: {
  value: string
  class?: string
  children?: Snippet
  onclick?: (event: MouseEvent) => void
  [key: string]: unknown
} = $props()

const context = getToggleGroupContext()
</script>

<ToggleGroup.Item
  data-slot="toggle-group-item"
  {value}
  class={toggleItemClasses(context.variant, context.size, cn('cursor-pointer', className))}
  {onclick}
  {...restProps}
>
  {@render children?.()}
</ToggleGroup.Item>

// apps/vue/src/ui/primitives/toggle-group/ToggleGroupItem.vue
<script setup lang="ts">
import { ToggleGroupItem } from 'reka-ui'
import { computed, inject } from 'vue'

import { cn } from '@/shared/lib/utils'

import { toggleItemClasses } from './toggleVariants'

const props = defineProps<{
  value: string
  class?: string
}>()

const context = inject<{ variant?: 'default' | 'outline'; size?: 'default' | 'sm' | 'lg' }>(
  'toggleGroupContext',
  {},
)

const classes = computed(() =>
  toggleItemClasses(context.variant, context.size, cn('cursor-pointer', props.class)),
)
</script>

<template>
  <ToggleGroupItem data-slot="toggle-group-item" :value="value" :class="classes">
    <slot />
  </ToggleGroupItem>
</template>
