// apps/vue/src/ui/primitives/dropdown-menu/DropdownMenuTrigger.vue
<script setup lang="ts">
import type { DropdownMenuTriggerProps } from 'reka-ui'
import { DropdownMenuTrigger, useForwardProps } from 'reka-ui'

const props = withDefaults(defineProps<DropdownMenuTriggerProps>(), {
  asChild: true,
})

const forwarded = useForwardProps(props)
</script>

<template>
  <DropdownMenuTrigger data-slot="dropdown-menu-trigger" v-bind="forwarded">
    <slot />
  </DropdownMenuTrigger>
</template>

// apps/solid/src/ui/primitives/dropdown-menu/DropdownMenuTrigger.tsx
import { DropdownMenu as DropdownMenuPrimitive } from '@kobalte/core/dropdown-menu'
import { type JSX, splitProps } from 'solid-js'

export type DropdownMenuTriggerProps = {
  as?: 'button' | 'div'
  class?: string
  children?: JSX.Element
}

export function DropdownMenuTrigger(props: DropdownMenuTriggerProps) {
  const [local, rest] = splitProps(props, ['as', 'class', 'children'])

  return (
    <DropdownMenuPrimitive.Trigger
      data-slot="dropdown-menu-trigger"
      as={local.as ?? 'button'}
      class={local.class}
      {...rest}
    >
      {local.children}
    </DropdownMenuPrimitive.Trigger>
  )
}
