// apps/react/src/ui/components/TextEditor/TextEditor.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react'
import {
  CanvasEntitySubtype,
  CanvasEntityType,
  DEFAULT_FONT_WEIGHT,
  DEFAULT_RECT_SIZE,
  DEFAULT_SCALE,
  DEFAULT_TEXT_AREA_HEIGHT,
  DEFAULT_TEXT_AREA_WIDTH,
  DoubleClickCustomEvent,
  FontStyle,
  isCanvasRect,
  isCanvasText,
  Point,
  SMALL_PADDING,
  TextDecoration,
} from '@infinite-canvas-x/canvas-engine'

import { CustomEvents } from '@/shared/interfaces'

import { TextEditorMenu } from './TextEditorMenu/TextEditorMenu'

import styles from './TextEditor.module.css'
import { useActiveLayer, useCanvas, useTextEditor } from '@/store'

export const TextEditor = () => {
  const { renderer, camera } = useCanvas()
  const { activeLayer } = useActiveLayer()
  const { isLayerEditable, text, textAlign, fontSize, bold, italic, underline, ...actions } =
    useTextEditor()

  const { setText, setTextAlign, setFontSize, setBold, setItalic, setUnderline } = actions

  const textareaRef = useRef<HTMLTextAreaElement | null>(null)

  const [editorPosition, setEditorPosition] = useState<Point>(() => new Point(0, 0))
  const [adaptiveFontSize, setAdaptiveFontSize] = useState(fontSize)

  const calculateFontSize = (currentFontSize: number): number => {
    const ref = textareaRef.current
    if (!ref || !activeLayer) return currentFontSize

    const { height, scale } = activeLayer.getOptions()
    const currentValue = ref.value
    let nextFontSize = currentFontSize

    if (ref.scrollHeight * scale > height - SMALL_PADDING) {
      nextFontSize = nextFontSize - 2
    }

    if (currentValue.length < text.length && nextFontSize < adaptiveFontSize) {
      ref.style.fontSize = `${nextFontSize + 2}px`

      if (ref.scrollHeight * scale <= height - SMALL_PADDING) {
        nextFontSize = nextFontSize + 2
      } else {
        ref.style.fontSize = `${nextFontSize}px`
      }
    }

    return nextFontSize
  }

  const handleTextChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    if (activeLayer) {
      setFontSize(calculateFontSize(fontSize))
      setText(e.target.value)
    }
  }

  const handleFontSizeChange = (fontSize: number) => {
    setAdaptiveFontSize(calculateFontSize(fontSize))
    setFontSize(fontSize)
  }

  const handleDoubleClick = useCallback(
    (e: CustomEvent<DoubleClickCustomEvent>) => {
      const currentActiveLayer = e.detail.layer || activeLayer
      if (!currentActiveLayer || !camera) return

      const clickPosition = camera.handleDoubleClick(e, currentActiveLayer)
      setEditorPosition(clickPosition)

      const textChild = currentActiveLayer.getChildByType(CanvasEntityType.TEXT)
      if (!textChild || !isCanvasText(textChild)) return

      const textOptions = textChild.getOptions()
      textChild.setOptions({ width: textOptions.width, height: textOptions.height })
      setText(textOptions.text)
      setTextAlign(textOptions.textAlign)
      setFontSize(textOptions.fontSize)
      setBold(Boolean(/bold/.test(textOptions.fontStyle)))
      setItalic(Boolean(/italic/.test(textOptions.fontStyle)))
      setUnderline(Boolean(/underline/.test(textOptions.textDecoration)))
    },
    [activeLayer, camera, setBold, setFontSize, setItalic, setText, setTextAlign, setUnderline],
  )

  useEffect(() => {
    if (textareaRef.current && isLayerEditable) {
      textareaRef.current.focus()
    }
  }, [isLayerEditable])

  useEffect(() => {
    window.addEventListener(
      CustomEvents.DOUBLE_CLICK,
      handleDoubleClick as unknown as EventListener,
    )
    return () =>
      window.removeEventListener(
        CustomEvents.DOUBLE_CLICK,
        handleDoubleClick as unknown as EventListener,
      )
  }, [activeLayer, handleDoubleClick])

  if (!activeLayer || !renderer) return null

  const rect = activeLayer.getChildByType(CanvasEntityType.RECT)
  if (!rect || !isCanvasRect(rect)) return null

  const { scale } = rect.getOptions()
  const transform = renderer.getTransformMatrix()
  const inverseScale = DEFAULT_SCALE / (transform.scaleX / transform.initialScale)
  const editorScale = scale / inverseScale
  const isVisible = activeLayer && isLayerEditable
  const isTextArea = rect.getSubtype() === CanvasEntitySubtype.TEXT

  const width = isTextArea ? DEFAULT_TEXT_AREA_WIDTH : DEFAULT_RECT_SIZE
  const height = isTextArea ? DEFAULT_TEXT_AREA_HEIGHT : DEFAULT_RECT_SIZE

  return (
    <>
      {isLayerEditable && (
        <TextEditorMenu
          textareaRef={textareaRef}
          position={editorPosition}
          onFontSizeChange={handleFontSizeChange}
        />
      )}
      <textarea
        id="text-editor"
        ref={textareaRef}
        value={text}
        className={styles.textEditor}
        placeholder="Enter text"
        onChange={handleTextChange}
        style={{
          visibility: isVisible ? 'visible' : 'hidden',
          left: editorPosition.x + SMALL_PADDING * editorScale,
          top: editorPosition.y + SMALL_PADDING * editorScale,
          width: width - SMALL_PADDING * 2,
          height: height - SMALL_PADDING * 2,
          transform: `scale(${editorScale})`,
          textAlign: textAlign,
          fontSize: `${fontSize}px`,
          fontStyle: italic ? FontStyle.ITALIC : undefined,
          fontWeight: bold ? FontStyle.BOLD : Number(DEFAULT_FONT_WEIGHT),
          textDecoration: underline ? TextDecoration.UNDERLINE : undefined,
        }}
      />
    </>
  )
}

// apps/vue/src/ui/components/TextEditor/TextEditor.vue
<script setup lang="ts">
import {
  CanvasEntitySubtype,
  CanvasEntityType,
  DEFAULT_FONT_WEIGHT,
  DEFAULT_RECT_SIZE,
  DEFAULT_SCALE,
  DEFAULT_TEXT_AREA_HEIGHT,
  DEFAULT_TEXT_AREA_WIDTH,
  type DoubleClickCustomEvent,
  FontStyle,
  isCanvasRect,
  isCanvasText,
  Point,
  SMALL_PADDING,
  TextDecoration,
} from '@infinite-canvas-x/canvas-engine'
import {
  type CSSProperties,
  computed,
  nextTick,
  onMounted,
  onUnmounted,
  ref,
  useCssModule,
  watch,
} from 'vue'

import { CustomEvents } from '@/shared/interfaces'

import TextEditorMenu from './TextEditorMenu/TextEditorMenu.vue'

import { useActiveLayer, useCanvas, useTextEditor } from '@/store'

const styles = useCssModule()

const canvas = useCanvas()
const activeLayerCtx = useActiveLayer()
const textEditorCtx = useTextEditor()

const textareaRef = ref<HTMLTextAreaElement | null>(null)
const editorPosition = ref(new Point(0, 0))
const adaptiveFontSize = ref(textEditorCtx.value.fontSize)

const renderer = computed(() => canvas.value.renderer)
const activeLayer = computed(() => activeLayerCtx.value.activeLayer)
const isLayerEditable = computed(() => textEditorCtx.value.isLayerEditable)
const text = computed(() => textEditorCtx.value.text)
const textAlign = computed(() => textEditorCtx.value.textAlign)
const fontSize = computed(() => textEditorCtx.value.fontSize)
const bold = computed(() => textEditorCtx.value.bold)
const italic = computed(() => textEditorCtx.value.italic)
const underline = computed(() => textEditorCtx.value.underline)

function calculateFontSize(currentFontSize: number): number {
  const el = textareaRef.value
  const layer = activeLayer.value
  if (!el || !layer) return currentFontSize

  const { height, scale } = layer.getOptions()
  const currentValue = el.value
  let nextFontSize = currentFontSize

  if (el.scrollHeight * scale > height - SMALL_PADDING) {
    nextFontSize = nextFontSize - 2
  }

  if (currentValue.length < text.value.length && nextFontSize < adaptiveFontSize.value) {
    el.style.fontSize = `${nextFontSize + 2}px`

    if (el.scrollHeight * scale <= height - SMALL_PADDING) {
      nextFontSize = nextFontSize + 2
    } else {
      el.style.fontSize = `${nextFontSize}px`
    }
  }

  return nextFontSize
}

function handleFontSizeChange(newFontSize: number) {
  adaptiveFontSize.value = calculateFontSize(newFontSize)
}

function handleTextChange(e: Event) {
  const layer = activeLayer.value
  if (!layer) return
  const target = e.target as HTMLTextAreaElement
  const ctx = textEditorCtx.value
  ctx.setFontSize(calculateFontSize(fontSize.value))
  ctx.setText(target.value)
}

const showEditor = computed(() => {
  if (!activeLayer.value || !renderer.value) return false
  const rect = activeLayer.value.getChildByType(CanvasEntityType.RECT)
  return Boolean(rect && isCanvasRect(rect))
})

async function focusTextarea() {
  await nextTick()
  textareaRef.value?.focus()
}

function handleDoubleClick(e: CustomEvent<DoubleClickCustomEvent>) {
  const cam = canvas.value.camera
  const currentActiveLayer = e.detail.layer || activeLayer.value
  if (!currentActiveLayer || !cam) return

  const clickPosition = cam.handleDoubleClick(e, currentActiveLayer)
  editorPosition.value = clickPosition

  const textChild = currentActiveLayer.getChildByType(CanvasEntityType.TEXT)
  if (textChild && isCanvasText(textChild)) {
    const textOptions = textChild.getOptions()
    textChild.setOptions({ width: textOptions.width, height: textOptions.height })
    const ctx = textEditorCtx.value
    ctx.setText(textOptions.text)
    ctx.setTextAlign(textOptions.textAlign)
    ctx.setFontSize(textOptions.fontSize)
    ctx.setBold(Boolean(/bold/.test(textOptions.fontStyle)))
    ctx.setItalic(Boolean(/italic/.test(textOptions.fontStyle)))
    ctx.setUnderline(Boolean(/underline/.test(textOptions.textDecoration)))
  }

  if (isLayerEditable.value) {
    focusTextarea()
  }
}

watch([showEditor, isLayerEditable], ([show, editable]) => {
  if (show && editable) {
    focusTextarea()
  }
})

onMounted(() => {
  window.addEventListener(CustomEvents.DOUBLE_CLICK, handleDoubleClick as EventListener)
})

onUnmounted(() => {
  window.removeEventListener(CustomEvents.DOUBLE_CLICK, handleDoubleClick as EventListener)
})

const editorStyle = computed((): CSSProperties => {
  const layer = activeLayer.value
  const rend = renderer.value
  if (!layer || !rend) return {}

  const rect = layer.getChildByType(CanvasEntityType.RECT)
  if (!rect || !isCanvasRect(rect)) return {}

  const { scale } = rect.getOptions()
  const transform = rend.getTransformMatrix()
  const inverseScale = DEFAULT_SCALE / (transform.scaleX / transform.initialScale)
  const editorScale = scale / inverseScale
  const isTextArea = rect.getSubtype() === CanvasEntitySubtype.TEXT
  const width = isTextArea ? DEFAULT_TEXT_AREA_WIDTH : DEFAULT_RECT_SIZE
  const height = isTextArea ? DEFAULT_TEXT_AREA_HEIGHT : DEFAULT_RECT_SIZE

  return {
    visibility: isLayerEditable.value ? 'visible' : 'hidden',
    left: `${editorPosition.value.x + SMALL_PADDING * editorScale}px`,
    top: `${editorPosition.value.y + SMALL_PADDING * editorScale}px`,
    width: `${width - SMALL_PADDING * 2}px`,
    height: `${height - SMALL_PADDING * 2}px`,
    transform: `scale(${editorScale})`,
    textAlign: textAlign.value as CSSProperties['textAlign'],
    fontSize: `${fontSize.value}px`,
    fontStyle: italic.value ? FontStyle.ITALIC : undefined,
    fontWeight: bold.value ? FontStyle.BOLD : Number(DEFAULT_FONT_WEIGHT),
    textDecoration: underline.value ? TextDecoration.UNDERLINE : undefined,
  }
})
</script>

<template>
  <template v-if="showEditor">
    <TextEditorMenu
      v-if="isLayerEditable"
      :textarea-ref="textareaRef"
      :position="editorPosition"
      @font-size-change="handleFontSizeChange"
    />
    <textarea
      id="text-editor"
      ref="textareaRef"
      :value="text"
      :class="styles.textEditor"
      placeholder="Enter text"
      :style="editorStyle"
      @input="handleTextChange"
    />
  </template>
</template>

<style module>
.textEditor {
  box-sizing: border-box;
  background: transparent;
  position: absolute;
  padding: 0;
  z-index: 10;
  line-break: anywhere;
  overflow: hidden;
  resize: none;
  border: none;
  outline: none;
  transform-origin: top left;
  text-align: center;
}

.textEditor::placeholder {
  color: var(--muted-foreground);
}

.textEditor:focus-visible {
  outline: none;
}

.textEditor:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
</style>
