// apps/svelte/src/ui/primitives/sheet/SheetTitle.svelte
<script lang="ts">
import { Dialog } from 'bits-ui'
import type { Snippet } from 'svelte'

import { cn } from '@/shared/lib/utils'

let { class: className, children }: { class?: string; children?: Snippet } = $props()
</script>

<Dialog.Title data-slot="sheet-title" class={cn('text-foreground font-semibold', className)}>
  {@render children?.()}
</Dialog.Title>

// apps/vue/src/ui/primitives/sheet/SheetTitle.vue
<script setup lang="ts">
import { DialogTitle } from 'reka-ui'
import { computed } from 'vue'

import { cn } from '@/shared/lib/utils'

const props = defineProps<{ class?: string }>()
const classes = computed(() => cn('text-foreground font-semibold', props.class))
</script>

<template>
  <DialogTitle data-slot="sheet-title" :class="classes">
    <slot />
  </DialogTitle>
</template>
