// apps/svelte/src/ui/primitives/sheet/SheetHeader.svelte
<script lang="ts">
import type { Snippet } from 'svelte'

import { cn } from '@/shared/lib/utils'

let { class: className, children }: { class?: string; children?: Snippet } = $props()
</script>

<div data-slot="sheet-header" class={cn('flex flex-col gap-1.5 p-4', className)}>
  {@render children?.()}
</div>

// apps/vue/src/ui/primitives/sheet/SheetHeader.vue
<script setup lang="ts">
import { computed } from 'vue'

import { cn } from '@/shared/lib/utils'

const props = defineProps<{ class?: string }>()
const classes = computed(() => cn('flex flex-col gap-1.5 p-4', props.class))
</script>

<template>
  <div data-slot="sheet-header" :class="classes">
    <slot />
  </div>
</template>
