// apps/svelte/src/ui/primitives/toggle-group/ToggleGroupItem.svelte
<script lang="ts">
import { ToggleGroup } from 'bits-ui'
import type { Snippet } from 'svelte'

import { cn } from '@/shared/lib/utils'

import { getToggleGroupContext } from './toggleGroupContext'
import { toggleItemClasses } from './toggleVariants'

let {
  value,
  class: className,
  children,
  onclick,
  ...restProps
}: {
  value: string
  class?: string
  children?: Snippet
  onclick?: (event: MouseEvent) => void
  [key: string]: unknown
} = $props()

const context = getToggleGroupContext()
</script>

<ToggleGroup.Item
  data-slot="toggle-group-item"
  {value}
  class={toggleItemClasses(context.variant, context.size, cn('cursor-pointer', className))}
  {onclick}
  {...restProps}
>
  {@render children?.()}
</ToggleGroup.Item>

// apps/solid/src/ui/primitives/toggle-group/ToggleGroupItem.tsx
import { ToggleGroup as ToggleGroupPrimitive } from '@kobalte/core/toggle-group'
import { type JSX, splitProps } from 'solid-js'

import { cn } from '@/shared/lib/utils'

import { useToggleGroupContext } from './toggleGroupContext'
import { toggleItemClasses } from './toggleVariants'

export type ToggleGroupItemProps = {
  value: string
  class?: string
  children?: JSX.Element
  'aria-label'?: string
  onClick?: (event: MouseEvent) => void
}

export function ToggleGroupItem(props: ToggleGroupItemProps) {
  const [local, rest] = splitProps(props, ['value', 'class', 'children', 'aria-label', 'onClick'])
  const context = useToggleGroupContext()

  return (
    <ToggleGroupPrimitive.Item
      data-slot="toggle-group-item"
      value={local.value}
      class={toggleItemClasses(context.variant, context.size, cn('cursor-pointer', local.class))}
      aria-label={local['aria-label']}
      onClick={local.onClick}
      {...rest}
    >
      {local.children}
    </ToggleGroupPrimitive.Item>
  )
}
