// apps/solid/src/ui/components/Canvas/CanvasView.tsx
import { createEffect, createMemo, createSignal, onCleanup, onMount } from 'solid-js'

import { DEFAULT_CURSOR } from '@/shared/constants'

import { useCanvasApp } from '@/adapters/solid/useCanvasApp'
import { useToolbar } from '@/store'

type CanvasViewProps = {
  setCanvasRef: (canvas: HTMLCanvasElement) => void
  setBackgroundCanvasRef: (backgroundCanvas: HTMLCanvasElement) => void
}

export function CanvasView(props: CanvasViewProps) {
  const getApp = useCanvasApp()
  const toolbar = useToolbar()

  const [canvasContainer, setCanvasContainer] = createSignal<HTMLDivElement | undefined>()
  const [mainCanvas, setMainCanvas] = createSignal<HTMLCanvasElement | null>(null)
  const [backgroundCanvas, setBackgroundCanvas] = createSignal<HTMLCanvasElement | null>(null)

  const cursor = createMemo(() => (getApp() ? toolbar().cursor : DEFAULT_CURSOR))

  createEffect(() => {
    const canvas = mainCanvas()
    if (canvas) {
      props.setCanvasRef(canvas)
    }
  })

  createEffect(() => {
    const canvas = backgroundCanvas()
    if (canvas) {
      props.setBackgroundCanvasRef(canvas)
    }
  })

  function handleZoomStopped() {
    getApp()?.getRenderManager()?.reDrawOnNextFrame({ forceRender: true })
  }

  createEffect(() => {
    const app = getApp()
    if (!app) {
      return
    }

    const unsubscribe = app.events.onZoomingStopped(handleZoomStopped)
    onCleanup(() => {
      unsubscribe()
    })
  })

  onMount(() => {
    const container = canvasContainer()
    if (!container) {
      return
    }

    const handleWheelPreventDefault = (event: WheelEvent) => event.preventDefault()
    container.addEventListener('wheel', handleWheelPreventDefault, { passive: false })

    onCleanup(() => {
      container.removeEventListener('wheel', handleWheelPreventDefault)
    })
  })

  return (
    <div ref={setCanvasContainer}>
      <canvas
        id="main-canvas"
        style={{ cursor: cursor() }}
        class="main-canvas"
        ref={setMainCanvas}
        onMouseMove={(event) => getApp()?.handlePointerMove(event)}
        onMouseDown={(event) => getApp()?.handlePointerDown(event)}
        onMouseUp={() => getApp()?.handlePointerUp()}
        onDblClick={(event) => getApp()?.handleDoubleClick(event)}
        onWheel={(event) => getApp()?.handleWheel(event)}
      />
      <canvas id="background-canvas" class="background-canvas" ref={setBackgroundCanvas} />
      <style>{`
        .main-canvas {
          position: absolute;
          background-color: transparent;
        }
        .background-canvas {
          position: absolute;
          z-index: -1;
          pointer-events: none;
          touch-action: none;
          user-select: none;
        }
      `}</style>
    </div>
  )
}

// apps/svelte/src/ui/components/Canvas/CanvasView.svelte
<script lang="ts">
import { onDestroy, onMount } from 'svelte'

import { DEFAULT_CURSOR } from '@/shared/constants'

import { useCanvasApp } from '@/adapters/svelte/useCanvasApp.svelte'
import { useToolbar } from '@/store/index.svelte'

type Props = {
  setCanvasRef: (canvas: HTMLCanvasElement) => void
  setBackgroundCanvasRef: (backgroundCanvas: HTMLCanvasElement) => void
}

let { setCanvasRef, setBackgroundCanvasRef }: Props = $props()

const getApp = useCanvasApp()
const getToolbar = useToolbar()

let canvasContainer: HTMLDivElement | undefined = $state()
let mainCanvas = $state<HTMLCanvasElement | null>(null)
let backgroundCanvas = $state<HTMLCanvasElement | null>(null)
let zoomUnsubscribe: (() => void) | null = null

const cursor = $derived(getApp() ? getToolbar().cursor : DEFAULT_CURSOR)

$effect(() => {
  if (mainCanvas) {
    setCanvasRef(mainCanvas)
  }
})

$effect(() => {
  if (backgroundCanvas) {
    setBackgroundCanvasRef(backgroundCanvas)
  }
})

function handleZoomStopped() {
  getApp()?.getRenderManager()?.reDrawOnNextFrame({ forceRender: true })
}

$effect(() => {
  zoomUnsubscribe?.()
  zoomUnsubscribe = null

  const app = getApp()
  if (!app) {
    return
  }

  zoomUnsubscribe = app.events.onZoomingStopped(handleZoomStopped)
})

onDestroy(() => {
  zoomUnsubscribe?.()
})

onMount(() => {
  const container = canvasContainer
  if (!container) {
    return
  }

  const handleWheelPreventDefault = (event: WheelEvent) => event.preventDefault()
  container.addEventListener('wheel', handleWheelPreventDefault, { passive: false })

  return () => {
    container.removeEventListener('wheel', handleWheelPreventDefault)
  }
})
</script>

<div bind:this={canvasContainer}>
  <canvas
    id="main-canvas"
    style:cursor={cursor}
    class="main-canvas"
    bind:this={mainCanvas}
    onmousemove={(event) => getApp()?.handlePointerMove(event)}
    onmousedown={(event) => getApp()?.handlePointerDown(event)}
    onmouseup={() => getApp()?.handlePointerUp()}
    ondblclick={(event) => getApp()?.handleDoubleClick(event)}
    onwheel={(event) => getApp()?.handleWheel(event)}
  ></canvas>
  <canvas
    id="background-canvas"
    class="background-canvas"
    bind:this={backgroundCanvas}
  ></canvas>
</div>

<style>
  .main-canvas {
    position: absolute;
    background-color: transparent;
  }

  .background-canvas {
    position: absolute;
    z-index: -1;
    pointer-events: none;
    touch-action: none;
    user-select: none;
  }
</style>
