// apps/svelte/src/ui/primitives/separator/Separator.svelte
<script lang="ts">
import { Separator } from 'bits-ui'

import { cn } from '@/shared/lib/utils'

let {
  orientation = 'horizontal',
  class: className,
}: {
  orientation?: 'horizontal' | 'vertical'
  class?: string
} = $props()
</script>

<Separator.Root
  data-slot="separator-root"
  {orientation}
  class={cn(
    'bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
    className,
  )}
/>

// src/ui/primitives/separator.tsx
import * as React from 'react'
import { Separator as SeparatorPrimitive } from 'radix-ui'

import { cn } from '@/shared/lib/utils'

function Separator({
  className,
  orientation = 'horizontal',
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator-root"
      decorative={decorative}
      orientation={orientation}
      className={cn(
        'bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        className,
      )}
      {...props}
    />
  )
}

export { Separator }
