// apps/solid/src/ui/primitives/dropdown-menu/DropdownMenuTrigger.tsx
import { DropdownMenu as DropdownMenuPrimitive } from '@kobalte/core/dropdown-menu'
import { type JSX, splitProps } from 'solid-js'

export type DropdownMenuTriggerProps = {
  as?: 'button' | 'div'
  class?: string
  children?: JSX.Element
}

export function DropdownMenuTrigger(props: DropdownMenuTriggerProps) {
  const [local, rest] = splitProps(props, ['as', 'class', 'children'])

  return (
    <DropdownMenuPrimitive.Trigger
      data-slot="dropdown-menu-trigger"
      as={local.as ?? 'button'}
      class={local.class}
      {...rest}
    >
      {local.children}
    </DropdownMenuPrimitive.Trigger>
  )
}

// apps/svelte/src/ui/primitives/dropdown-menu/DropdownMenuTrigger.svelte
<script lang="ts">
import { DropdownMenu } from 'bits-ui'
import type { Snippet } from 'svelte'

let { children }: { children?: Snippet } = $props()
</script>

<DropdownMenu.Trigger data-slot="dropdown-menu-trigger">
  {#snippet child({ props })}
    <div {...props}>
      {@render children?.()}
    </div>
  {/snippet}
</DropdownMenu.Trigger>
