// apps/svelte/src/ui/primitives/sheet/SheetHeader.svelte
<script lang="ts">
import type { Snippet } from 'svelte'

import { cn } from '@/shared/lib/utils'

let { class: className, children }: { class?: string; children?: Snippet } = $props()
</script>

<div data-slot="sheet-header" class={cn('flex flex-col gap-1.5 p-4', className)}>
  {@render children?.()}
</div>

// apps/solid/src/ui/primitives/sheet/SheetHeader.tsx
import { type JSX, splitProps } from 'solid-js'

import { cn } from '@/shared/lib/utils'

export type SheetHeaderProps = {
  class?: string
  children?: JSX.Element
}

export function SheetHeader(props: SheetHeaderProps) {
  const [local] = splitProps(props, ['class', 'children'])

  return (
    <div data-slot="sheet-header" class={cn('flex flex-col gap-1.5 p-4', local.class)}>
      {local.children}
    </div>
  )
}
