// apps/solid/src/ui/components/ElementsPanel/ElementsPanel.tsx
import ImageIcon from 'lucide-solid/icons/image'
import { createSignal } from 'solid-js'

import { Button } from '@/ui/primitives/button/Button'

import { ImageDrawer } from './ImageDrawer.tsx'

import { useCanvasApp } from '@/adapters/solid/useCanvasApp'

export function ElementsPanel() {
  const getApp = useCanvasApp()
  const [isImagesOpen, setIsImagesOpen] = createSignal(false)

  function handleOpenDrawer() {
    setIsImagesOpen(true)
    getApp()?.deselectActiveLayer()
  }

  return (
    <>
      <div class="fixed left-0 top-0 h-full w-14 bg-white border-r border-gray-200 flex flex-col items-center py-3 z-40">
        <div class="mb-4">
          <div class="w-7 h-7 bg-gray-900 rounded-lg flex items-center justify-center">
            <span class="text-white font-bold text-base italic">K</span>
          </div>
        </div>

        <div class="flex flex-col gap-1">
          <Button
            variant="ghost"
            size="sm"
            class="w-8 h-8 p-0 text-gray-700 hover:text-black hover:bg-gray-100"
            onClick={handleOpenDrawer}
          >
            <ImageIcon class="w-4 h-4" />
            <span class="sr-only">Images</span>
          </Button>
        </div>
      </div>

      <ImageDrawer open={isImagesOpen()} onOpenChange={setIsImagesOpen} />
    </>
  )
}

// apps/react/src/ui/components/ElementsPanel/ElementsPanel.tsx
import { useCallback, useMemo, useState } from 'react'
import { ImageIcon } from 'lucide-react'

import { Button } from '@/ui/primitives/button'

import { ImageDrawer } from './ImageDrawer'

import { useCanvasApp } from '@/adapters/react/useCanvasApp'

export function ElementsPanel() {
  const [isImagesOpen, setIsImagesOpen] = useState(false)
  const app = useCanvasApp()

  const handleOpenDrawer = useCallback(
    (open: boolean) => {
      setIsImagesOpen(open)
      app?.deselectActiveLayer()
    },
    [app],
  )

  const sidebarItems = useMemo(
    () => [{ icon: ImageIcon, label: 'Images', onClick: () => handleOpenDrawer(true) }],
    [handleOpenDrawer],
  )

  return (
    <>
      <div className="fixed left-0 top-0 h-full w-14 bg-white border-r border-gray-200 flex flex-col items-center py-3 z-40">
        <div className="mb-4">
          <div className="w-7 h-7 bg-gray-900 rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-base italic">K</span>
          </div>
        </div>

        <div className="flex flex-col gap-1">
          {sidebarItems.map((item, index) => (
            <Button
              key={index}
              variant="ghost"
              size="sm"
              className="w-8 h-8 p-0 text-gray-700 hover:text-black hover:bg-gray-100"
              onClick={item.onClick}
            >
              <item.icon className="w-4 h-4" />
              <span className="sr-only">{item.label}</span>
            </Button>
          ))}
        </div>
      </div>

      <ImageDrawer open={isImagesOpen} onOpenChange={handleOpenDrawer} />
    </>
  )
}
