// src/components/ui/toggle-group.tsx
import * as React from 'react';
import { ToggleGroup as ToggleGroupPrimitive } from 'radix-ui';
import { type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';
import { toggleVariants } from '@/components/ui/toggle';

const ToggleGroupContext = React.createContext<VariantProps<typeof toggleVariants>>({
  size: 'default',
  variant: 'default',
});

function ToggleGroup({
  className,
  variant,
  size,
  children,
  ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Root> & VariantProps<typeof toggleVariants>) {
  return (
    <ToggleGroupPrimitive.Root
      data-slot="toggle-group"
      data-variant={variant}
      data-size={size}
      className={cn(
        'group/toggle-group flex w-fit items-center rounded-md data-[variant=outline]:shadow-xs',
        className,
      )}
      {...props}
    >
      <ToggleGroupContext.Provider value={{ variant, size }}>{children}</ToggleGroupContext.Provider>
    </ToggleGroupPrimitive.Root>
  );
}

function ToggleGroupItem({
  className,
  children,
  variant,
  size,
  ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Item> & VariantProps<typeof toggleVariants>) {
  const context = React.useContext(ToggleGroupContext);

  return (
    <ToggleGroupPrimitive.Item
      data-slot="toggle-group-item"
      data-variant={context.variant || variant}
      data-size={context.size || size}
      className={cn(
        toggleVariants({
          variant: context.variant || variant,
          size: context.size || size,
        }),
        'min-w-0 flex-1 shrink-0 rounded-none shadow-none first:rounded-l-md last:rounded-r-md focus:z-10 focus-visible:z-10 data-[variant=outline]:border-l-0 data-[variant=outline]:first:border-l',
        className,
      )}
      {...props}
    >
      {children}
    </ToggleGroupPrimitive.Item>
  );
}

export { ToggleGroup, ToggleGroupItem };

// apps/svelte/src/ui/primitives/toggle-group/ToggleGroup.svelte
<script lang="ts">
import { ToggleGroup } from 'bits-ui'
import type { Snippet } from 'svelte'

import { cn } from '@/shared/lib/utils'

import { setToggleGroupContext } from './toggleGroupContext'
import type { ToggleVariants } from './toggleVariants'

type Props = {
  type?: 'single' | 'multiple'
  value?: string | string[]
  variant?: ToggleVariants['variant']
  size?: ToggleVariants['size']
  class?: string
  children?: Snippet
}

let {
  type = 'single',
  value = $bindable<string | string[]>(type === 'multiple' ? [] : ''),
  variant = 'default',
  size = 'default',
  class: className,
  children,
}: Props = $props()

$effect(() => {
  setToggleGroupContext({ variant, size })
})
</script>

{#if type === 'multiple'}
  <ToggleGroup.Root
    data-slot="toggle-group"
    type="multiple"
    bind:value={value as string[]}
    data-variant={variant}
    data-size={size}
    class={cn(
      'group/toggle-group flex w-fit items-center rounded-md data-[variant=outline]:shadow-xs',
      className,
    )}
  >
    {@render children?.()}
  </ToggleGroup.Root>
{:else}
  <ToggleGroup.Root
    data-slot="toggle-group"
    type="single"
    bind:value={value as string}
    data-variant={variant}
    data-size={size}
    class={cn(
      'group/toggle-group flex w-fit items-center rounded-md data-[variant=outline]:shadow-xs',
      className,
    )}
  >
    {@render children?.()}
  </ToggleGroup.Root>
{/if}
