// apps/react/src/adapters/react/useCanvasSliceManager.ts
import { useContext } from 'react'

import { CanvasSliceManagerContext } from './CanvasSliceManagerContext'

export function useCanvasSliceManager() {
  const manager = useContext(CanvasSliceManagerContext)

  if (!manager) {
    throw new Error('useCanvasSliceManager must be used within CanvasAppProvider')
  }

  return manager
}

// apps/solid/src/adapters/solid/useCanvasSliceManager.ts
import { useContext } from 'solid-js'

import { CanvasSliceManagerContext } from './CanvasSliceManagerContext'

export function useCanvasSliceManager() {
  const manager = useContext(CanvasSliceManagerContext)

  if (!manager) {
    throw new Error('useCanvasSliceManager must be used within CanvasAppProvider')
  }

  return manager
}
